version: '3'

services:
#  mailer:
#    container_name: mailer
#    image: schickling/mailcatcher
#    ports:
#      - "1080:1080"
#      - "1025:1025"
#    networks:
#      - internal
#  database:
#   image: postgres:${POSTGRES_VERSION:-15}-alpine
#   container_name: sportdb
#   environment:
#     POSTGRES_DB: sport_camp
#     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#     POSTGRES_USER: ${POSTGRES_USER:-app}
#   ports:
#     - "5432:5432"
#   networks:
#     - internal
#   volumes:
#     - database_data:/var/lib/postgresql/data:rw

  symfony:
    container_name: symfony
    build: ./Dockerfile
    volumes:
      - ../:/workspaces:cached
    network_mode: service:db
    command: sleep infinity
#    networks:
#      - internal
#    working_dir: /www
#    volumes:
#      - app:/www/

#  nginx:
#    depends_on:
#      - symfony
#    build: ./docker/nginx
#    networks:
#      - internal
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#      - app:/www/
#      - ./var/log/nginx/:/www/var/log/nginx

#  rabbitmq:
#    image: rabbitmq:3.11-management
#    container_name: rabbitmq
#    networks:
#      - internal
#    environment:
#      RABBITMQ_DEFAULT_USER: "user"
#      RABBITMQ_DEFAULT_PASS: "password"
#    ports:
#      - '5672:5672'
#      - '15672:15672'

#volumes:
#  database_data:
#  app:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: './'

#networks:
#  internal:
#    driver: bridge
